---
title: "Sonoma State University - ICLM Analysis (Data from 6 Regular Terms)"
author: "Rich McGowan"
date: "November 25, 2018"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```
###  Initiate the Workspace and Import the 2 Data Sets from CSV Files
###  Produced by CS Queries
```{r Initiate and Import Data, echo=FALSE}
setwd("C:/Users/Richard/OneDrive/Rich Files/SSU/2018/SonomaStateICLM/project")
library(readr)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggplot2)
library(knitr)
library(kableExtra)
library(data.table)
library(tinytex)
#Read in the CSV data produced from Campus SOlutions Query and saved in local folder
ICLM_MAIN <- read_csv("ICLM_MAIN.csv",col_names = TRUE)
```
###  Munge the data sets
```{r Munge, echo=TRUE}
ICLM_MAIN$AdmitType <- factor(ICLM_MAIN$AdmitType)
UGRD_MAIN <- data.table(ICLM_MAIN %>% filter(Career == 'UGRD',UnitsTakenPrgrss > 0))
PBAC_MAIN <- data.table(ICLM_MAIN %>% filter(Career == 'PBAC',UnitsTakenPrgrss > 0))
#Calculate Undergraduate FTE Statistics taking the 3 Year Average by dividing by 6 (regular terms)
UGRD_FTE_THREEYRAVG <- UGRD_MAIN %>% group_by(StdntCollege,Major,CrseCollege) %>% summarize(FTES= round(sum(UnitsTakenPrgrss)/15)/6)
#Sum the Numeric Columns
#myNumCols <- which(unlist(lapply(UGRD_FTE_THREEYRAVG,is.numeric)))
#UGRD_FTE_THREEYRAVG[(nrow(UGRD_FTE_THREEYRAVG) + 1), myNumCols] <- colSums(round(UGRD_FTE_THREEYRAVG[, myNumCols]), na.rm=TRUE)
#Add the TOTAL row label to the last row
#UGRD_FTE_THREEYRAVG[(nrow(UGRD_FTE_THREEYRAVG)), ncol(UGRD_FTE_THREEYRAVG)-4] <- 'TOTAL'

```
###  Pivot Table of FTES UGRD College/Major by Course/College
```{r Create Pivot, echo=TRUE}
Major_Course_College_Pivot <- dcast(UGRD_FTE_THREEYRAVG, StdntCollege+Major~CrseCollege)
Major_Course_College_Pivot %>% group_by(StdntCollege,Major) %>% summarise(`Arts and Humanities`,`Business and Economics`,Education,`Science & Technology`,`Social Sciences`,`University-wide`)
```

###  Output of FTES UGRD Statistics (Average of 3 Years)
```{r Outuput1, echo=TRUE}
kable(Major_Course_College_Pivot) %>% 
kable_styling("striped", full_width = F, position = "center", font_size = 10)

```
###  Output of Undergraduate College Pivot
```{r Outuput2, echo=TRUE}
kable(College_Pivot) %>% 
kable_styling("striped", full_width = F, position = "center", font_size = 10)
```
###  Plot 1 Bar Chart
```{r}
UGRD_FTE_THREEYRAVG %>% ggplot(aes(x=AdmitType,y=TotalUnits,fill=StdntCollege))+
  geom_bar(stat="identity", width=0.5)+
  theme_minimal()
```
### Plot 2 - Bar Chart
```{r}
College_Pivot %>% ggplot(aes(x=StdntCollege,y=TotUnits,fill=CrseCollege)) +
  geom_bar(stat="identity", width=0.75) + coord_flip() +
  theme(legend.title = element_text(colour="blue", size=8, face="bold"))+
  theme(legend.text = element_text(colour="blue", size = 8, face = "bold"))+
  ylab("Total Units")+xlab("Students' Major College")
```

